# Generated by Django 2.2.6 on 2019-11-15 18:42

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20191115_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('state', models.CharField(max_length=200, verbose_name='state')),
                ('zipcode', models.CharField(max_length=10, verbose_name='zipcode')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(choices=[('K5', 'K-5 School'), ('MS', '6-8 School'), ('HS', 'High School'), ('UN', 'University')], default='NA', max_length=2, verbose_name='school grade')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAthlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('G', 'Girl'), ('B', 'Boy')], default='B', max_length=1, verbose_name='gender')),
                ('position', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('SS', 'Shortstop'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('OF', 'OutField')], max_length=10), size=8), null=True, size=8)),
                ('graduation_date', models.DateField(blank=True, help_text='If applicable.', null=True, verbose_name='date of graduation')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='bio')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
