# Generated by Django 2.2.6 on 2019-10-29 18:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentathlete',
            name='position',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('OF', 'Out Field')], max_length=10), size=8), default=['P'], size=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentathlete',
            name='gender',
            field=models.CharField(choices=[('G', 'Girl'), ('B', 'Boy')], default='B', max_length=1, verbose_name='gender'),
        ),
    ]
