# Generated by Django 2.2.6 on 2019-10-29 20:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0002_auto_20191029_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentathlete',
            name='position',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('OF', 'Out Field')], max_length=10), size=8), null=True, size=8),
        ),
    ]
