# Generated by Django 2.2.6 on 2019-10-31 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_proathleteprofile_studentathleteprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=250)),
                ('age', models.SmallIntegerField(default=0, verbose_name='age')),
                ('gender', models.CharField(choices=[('G', 'Girl'), ('B', 'Boy')], default='B', max_length=1, verbose_name='gender')),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name='birth place')),
                ('bats', models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('S', 'Switch')], default='R', max_length=1, verbose_name='bats')),
                ('throws', models.CharField(choices=[('R', 'Right'), ('L', 'Left')], default='R', max_length=1, verbose_name='throws')),
                ('weight', models.SmallIntegerField(verbose_name='weight')),
                ('school', models.CharField(max_length=200, verbose_name='School')),
                ('position', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('SS', 'Shortstop'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('OF', 'OutField')], default='P', max_length=2, verbose_name='position')),
                ('is_professional', models.BooleanField(default=False)),
                ('draft_round', models.SmallIntegerField(default='1', verbose_name='Round:')),
                ('draft_pick', models.SmallIntegerField(default=0, verbose_name='Pick:')),
                ('stat_link', models.URLField(verbose_name='stats')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.DeleteModel(
            name='ProAthleteProfile',
        ),
    ]
