# Generated by Django 2.2.6 on 2019-11-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Pitcher', 'Pitcher'), ('Catcher', 'Catcher'), ('1B', 'First Base'), ('SS', 'Shortstop'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('OF', 'OutField')], default='P', max_length=250),
        ),
    ]
