# Generated by Django 2.2.6 on 2019-10-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191031_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='draft_pick',
            field=models.SmallIntegerField(null=True, verbose_name='Pick:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='draft_round',
            field=models.SmallIntegerField(null=True, verbose_name='Round:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stat_link',
            field=models.URLField(null=True, verbose_name='stats'),
        ),
        migrations.DeleteModel(
            name='StudentAthleteProfile',
        ),
    ]
