# Generated by Django 2.2.6 on 2019-10-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191031_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bats',
            field=models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('S', 'Switch')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='draft_pick',
            field=models.SmallIntegerField(null=True, verbose_name='pick:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='draft_round',
            field=models.SmallIntegerField(null=True, verbose_name='round:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('G', 'Girl'), ('B', 'Boy')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('SS', 'Shortstop'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('OF', 'OutField')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='throws',
            field=models.CharField(choices=[('R', 'Right'), ('L', 'Left')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.SmallIntegerField(),
        ),
    ]
