# Generated by Django 2.2.6 on 2019-11-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_team_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_website',
            field=models.URLField(blank=True, null=True, verbose_name='team website'),
        ),
    ]
