# Generated by Django 2.2.6 on 2019-10-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191031_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='draft_pick',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='pick:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='draft_round',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='round:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stat_link',
            field=models.URLField(blank=True, null=True, verbose_name='stats'),
        ),
    ]
