# Generated by Django 2.2.6 on 2019-10-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191031_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_place',
            new_name='location',
        ),
    ]
