# Generated by Django 2.2.6 on 2019-10-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191031_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='graduation_date',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
