# Generated by Django 2.2.6 on 2019-11-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191101_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lessons',
            field=models.CharField(choices=[('Pitching Lessons', 'Pitching Lessons'), ('Hitting Lessons', 'Hitting Lessons'), ('Fielding Lessons', 'Fielding Lessons'), ('Fundamental Drills', 'fundamental Drills'), ('Conditioning & Training', 'Conditioning Training')], default='Hitting Lessons', max_length=200),
        ),
    ]
