# Generated by Django 2.2.6 on 2019-11-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.CharField(choices=[('Pitching', 'Pitching'), ('Hitting', 'Hitting'), ('Fielding', 'Fielding')], default='Hitting', max_length=200),
        ),
    ]
