# Generated by Django 2.2.6 on 2019-11-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20191107_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lessons',
            field=models.CharField(choices=[('PITCHING', 'Pitching Lessons'), ('HITTING', 'Hitting Lessons'), ('FIELDING', 'Fielding Lessons'), ('FUNDAMENTALS', 'Fundamental Drills'), ('CONDITIONING', 'Conditioning Training')], default='Hitting Lessons', max_length=200),
        ),
    ]
