# Generated by Django 2.2.6 on 2019-11-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191107_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.IntegerField(default=50.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.SmallIntegerField(max_length=200),
        ),
    ]
