# Generated by Django 2.2.6 on 2019-11-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20191109_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='booking_fee',
            field=models.IntegerField(default='50', max_length=200),
        ),
    ]
