# Generated by Django 2.2.6 on 2019-11-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_booking_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='booking_fee',
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
