# Generated by Django 2.2.6 on 2019-11-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20191111_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lessons',
            field=models.CharField(choices=[('PITCHING', 'Pitching Lessons'), ('HITTING', 'Hitting Lessons'), ('FIELDING', 'Fielding Lessons')], default='Hitting Lessons', max_length=200),
        ),
    ]
