# Generated by Django 2.2.6 on 2019-11-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20191112_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mlb_club',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='team_class',
            field=models.CharField(choices=[('Rookie Leauge', 'Rookie League'), ('Low A', 'Low A'), ('High A', 'Hige A'), ('AA', 'AA'), ('AAA', 'AAA'), ('Major League', 'Major League')], default='AA', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
