# Generated by Django 2.2.6 on 2019-11-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='fee',
        ),
    ]
