# Generated by Django 2.2.6 on 2019-11-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='updated_at',
            new_name='avialbility_end',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='created_at',
            new_name='avialbility_start',
        ),
    ]
